/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 接続情報（JS 向け） */
export interface ConnectionConfig {
  baseUrl: string
  apiKey: string
  apiVersion: string
}
/** JSON を正規化（不要キー除外 + キーソート） */
export declare function normalize(value: any): any
/** キーをソートして JSON 文字列化 */
export declare function sortedJsonStringify(value: any, indent?: number | undefined | null): string
/** サイトパッケージ JSON を読み込んでスキーマを生成 */
export declare function loadSitePackage(path: string): JsPackageSchema
/** サイトパッケージ JSON（オブジェクト）からスキーマを生成 */
export declare function parseSitePackage(package: any): JsPackageSchema
export type JsPleasanterClient = PleasanterClient
/** Node.js 向け Pleasanter クライアント */
export declare class PleasanterClient {
  /**
   * 新しいクライアントを作成
   *
   * ```js
   * const client = new PleasanterClient({
   *   baseUrl: 'https://pleasanter.example.com',
   *   apiKey: 'your-key',
   *   apiVersion: '1.1',
   * })
   * ```
   */
  constructor(config: JsConnectionConfig)
  /** サイト情報を取得 */
  getSite(siteId: number): Promise<any>
  /** サイト設定を更新 */
  updateSite(siteId: number, siteData: any): Promise<void>
  /**
   * サイトを作成（親サイト ID 配下に新規作成）
   * 戻り値: 作成されたサイト ID
   *
   * ```js
   * const siteId = await client.createSite(parentId, {
   *   Title: 'ユーザーマスタ',
   *   ReferenceType: 'Results',
   *   SiteSettings: { ... }
   * })
   * ```
   */
  createSite(parentId: number, siteData: any): Promise<number>
  /**
   * サイトを削除
   *
   * ```js
   * await client.deleteSite(12345)
   * ```
   */
  deleteSite(siteId: number): Promise<void>
  /** レコードデータを全件取得 */
  getRecords(siteId: number): Promise<Array<any>>
  /**
   * レコードデータを取得（オプション付き）
   *
   * ```js
   * const records = await client.getRecordsWithOptions(12345, {
   *   ApiDataType: 'KeyValues',
   *   ApiColumnKeyDisplayType: 'LabelText',
   *   GridColumns: ['ClassA', 'ClassB'],
   *   ColumnFilterHash: { ClassA: '["value"]' }
   * })
   * ```
   */
  getRecordsWithOptions(siteId: number, options?: any | undefined | null): Promise<Array<any>>
  /**
   * 単一レコードを取得
   *
   * ```js
   * const record = await client.getRecord(12345, {
   *   ApiDataType: 'KeyValues',
   *   ApiColumnKeyDisplayType: 'LabelText'
   * })
   * ```
   */
  getRecord(recordId: number, options?: any | undefined | null): Promise<any>
  /**
   * レコードを作成（戻り値: 作成されたレコード ID）
   *
   * ```js
   * const recordId = await client.createRecord(12345, {
   *   ClassHash: { ClassA: 'value' }
   * })
   * ```
   */
  createRecord(siteId: number, data: any): Promise<number>
  /**
   * レコードを更新
   *
   * ```js
   * await client.updateRecord(12345, {
   *   ClassHash: { ClassA: 'new-value' }
   * })
   * ```
   */
  updateRecord(recordId: number, data: any): Promise<void>
  /**
   * レコードを削除
   *
   * ```js
   * await client.deleteRecord(12345)
   * ```
   */
  deleteRecord(recordId: number): Promise<void>
}
export type JsPackageSchema = PackageSchema
/** Node.js 向けパッケージスキーマ */
export declare class PackageSchema {
  /** JSON からパッケージスキーマを構築（内部用） */
  constructor(package: any)
  /** ルートサイト ID を取得 */
  get baseSiteId(): number
  /** サーバー URL を取得 */
  get serverUrl(): string | null
  /** サイト一覧（タイトル）を取得 */
  getSiteTitles(): Array<string>
  /** タイトルからサイト ID を取得 */
  getSiteId(title: string): number | null
  /** タイトルからサイトスキーマを取得 */
  getSite(title: string): JsSiteSchema | null
  /** サイト ID からサイトスキーマを取得 */
  getSiteById(siteId: number): JsSiteSchema | null
  /** スキーマ全体を JSON として取得 */
  toJson(): any
}
export type JsSiteSchema = SiteSchema
/** Node.js 向けサイトスキーマ */
export declare class SiteSchema {
  /** ダミーコンストラクタ（napi-rs の制約回避用、直接使用禁止） */
  constructor()
  /** サイト ID を取得 */
  get siteId(): number
  /** タイトルを取得 */
  get title(): string
  /** リファレンスタイプを取得 */
  get referenceType(): string
  /** ラベル名からカラム名を取得 */
  getColumnName(label: string): string | null
  /** カラム名からラベル名を取得 */
  getLabel(columnName: string): string | null
  /** 全カラム名を取得 */
  getColumnNames(): Array<string>
  /** 全ラベルを取得 */
  getLabels(): Array<string>
  /**
   * カラム名から選択肢一覧を取得
   *
   * ```js
   * const choices = site.getChoices('Status')
   * // → [{ value: '100', label: '未掲載', shortLabel: '未掲載', color: null }, ...]
   * ```
   */
  getChoices(columnName: string): Array<any>
  /** スキーマを JSON として取得 */
  toJson(): any
}
