// AUTO-GENERATED — do not edit manually.
// Generated by pleasync from C:\Users\NT-210174\Desktop\projects\github\pleasync\examples\nextjs\pleasync.schema.yaml 

/* eslint-disable */
/* @ts-nocheck */
import { Engine, ModelCollection } from '@pleasync/orm';
import type { ModelDef, WhereOperator, OrderByDirection } from '@pleasync/orm';

// === shared choices ===
export type ProgressStatus = 100 | 200 | 900;

// === customer ===
export interface CustomerRecord {
  id: number;
  title: string;
  body: string;
  status: ProgressStatus;
  createdAt: Date;
  updatedAt: Date;
}

export interface CustomerCreateInput {
  title: string;
  body?: string;
  status?: ProgressStatus;
}

export interface CustomerUpdateInput {
  title?: string;
  body?: string;
  status?: ProgressStatus;
}

export interface CustomerWhere {
  id?: WhereOperator<number>;
  title?: WhereOperator<string>;
  body?: WhereOperator<string>;
  status?: WhereOperator<ProgressStatus>;
}

export interface CustomerOrderBy {
  id?: OrderByDirection;
  title?: OrderByDirection;
  body?: OrderByDirection;
  status?: OrderByDirection;
}

class CustomerCollection extends ModelCollection<
  CustomerRecord,
  CustomerCreateInput,
  CustomerUpdateInput,
  CustomerWhere,
  CustomerOrderBy
> {
  protected readonly modelDef: ModelDef = {
    type: "Results",
    parentId: 35534,
    siteId: 35535,
    fieldMap: {
      title: { slot: "Title", type: "text" },
      body: { slot: "Body", type: "text" },
      status: { slot: "Status", type: "status" },
    },
  };
}

// === issue ===
export interface IssueRecord {
  id: number;
  title: string;
  body: string;
  status: ProgressStatus;
  startDate: Date | string;
  completionDate: Date | string;
  createdAt: Date;
  updatedAt: Date;
}

export interface IssueCreateInput {
  title: string;
  body?: string;
  status?: ProgressStatus;
  startDate?: Date | string;
  completionDate?: Date | string;
}

export interface IssueUpdateInput {
  title?: string;
  body?: string;
  status?: ProgressStatus;
  startDate?: Date | string;
  completionDate?: Date | string;
}

export interface IssueWhere {
  id?: WhereOperator<number>;
  title?: WhereOperator<string>;
  body?: WhereOperator<string>;
  status?: WhereOperator<ProgressStatus>;
  startDate?: WhereOperator<Date | string>;
  completionDate?: WhereOperator<Date | string>;
}

export interface IssueOrderBy {
  id?: OrderByDirection;
  title?: OrderByDirection;
  body?: OrderByDirection;
  status?: OrderByDirection;
  startDate?: OrderByDirection;
  completionDate?: OrderByDirection;
}

class IssueCollection extends ModelCollection<
  IssueRecord,
  IssueCreateInput,
  IssueUpdateInput,
  IssueWhere,
  IssueOrderBy
> {
  protected readonly modelDef: ModelDef = {
    type: "Issues",
    parentId: 35534,
    siteId: 35536,
    fieldMap: {
      title: { slot: "Title", type: "text" },
      body: { slot: "Body", type: "text" },
      status: { slot: "Status", type: "status" },
      startDate: { slot: "StartTime", type: "datetime" },
      completionDate: { slot: "CompletionTime", type: "datetime" },
    },
  };
}

// === client ===

export interface PleasyncClientConfig {
  baseUrl: string;
  apiKey: string;
  apiVersion?: string;
}

export class PleasyncClient {
  readonly customer: CustomerCollection;
  readonly issue: IssueCollection;

  private constructor(engine: Engine) {
    this.customer = new CustomerCollection(engine);
    this.issue = new IssueCollection(engine);
  }

  /** 設定から PleasyncClient を構築（@pleasync/client を内部 require） */
  static async fromConfig(config: PleasyncClientConfig): Promise<PleasyncClient> {
    const engine = await Engine.fromConfig(config);
    return new PleasyncClient(engine);
  }

  /** Engine を直接渡す（テスト用） */
  static fromEngine(engine: Engine): PleasyncClient {
    return new PleasyncClient(engine);
  }
}
