import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, resolve } from 'node:path';
import { stringify as stringifyYaml } from 'yaml';
import { Engine } from '@pleasync/orm';
import type { SchemaAst } from '@pleasync/schema';
import { siteToModel, type RawSite } from './introspect.js';

export interface IntrospectCommandOptions {
  siteIds: number[];
  out?: string;
  baseUrl?: string;
  apiKey?: string;
  apiVersion?: string;
  cwd?: string;
  /** テスト用: getSite を直接注入（環境ごとの I/O を回避） */
  fetchSite?: (siteId: number) => Promise<RawSite>;
}

/**
 * 指定 siteId の Pleasanter サイトを取得して schema YAML を構築する。
 *
 * - --out 指定で書き込み、それ以外は YAML 文字列を返すのみ（呼び出し元が stdout に出す）
 */
export async function runIntrospect(
  options: IntrospectCommandOptions,
): Promise<{
  yaml: string;
  outputPath: string | null;
  modelCount: number;
}> {
  if (options.siteIds.length === 0) {
    throw new Error('introspect requires at least one siteId');
  }

  const fetchSite = options.fetchSite ?? (await defaultFetcher(options));

  const ast: SchemaAst = { version: '1', models: {} };
  const usedNames = new Set<string>();

  for (const siteId of options.siteIds) {
    const raw = await fetchSite(siteId);
    const { name, model } = siteToModel(raw);

    let unique = name;
    let i = 2;
    while (usedNames.has(unique)) {
      unique = `${name}${i}`;
      i += 1;
    }
    usedNames.add(unique);
    ast.models[unique] = model;
  }

  const yaml = serializeSchema(ast);

  if (options.out) {
    const cwd = options.cwd ?? process.cwd();
    const outPath = isAbsolute(options.out)
      ? options.out
      : resolve(cwd, options.out);
    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, yaml, 'utf-8');
    return { yaml, outputPath: outPath, modelCount: options.siteIds.length };
  }

  return { yaml, outputPath: null, modelCount: options.siteIds.length };
}

async function defaultFetcher(
  options: IntrospectCommandOptions,
): Promise<(siteId: number) => Promise<RawSite>> {
  const baseUrl = options.baseUrl ?? process.env.PLEASANTER_BASE_URL;
  const apiKey = options.apiKey ?? process.env.PLEASANTER_API_KEY;
  const apiVersion = options.apiVersion ?? process.env.PLEASANTER_API_VERSION ?? '1.1';

  if (!baseUrl) {
    throw new Error(
      'PLEASANTER_BASE_URL is required (or pass --base-url, or set env)',
    );
  }
  if (!apiKey) {
    throw new Error(
      'PLEASANTER_API_KEY is required (or pass --api-key, or set env)',
    );
  }

  const engine = await Engine.fromConfig({ baseUrl, apiKey, apiVersion });
  return async (siteId: number) => {
    const raw = await engine.api_().getSite(siteId);
    return raw as RawSite;
  };
}

/** SchemaAst を YAML 文字列に。先頭にコメント、適度なクオート抑制。 */
export function serializeSchema(ast: SchemaAst): string {
  const header = [
    '# Auto-generated by `pleasync introspect`',
    '#',
    '# Pleasanter から逆生成された schema。',
    '# 必要に応じて model 名・field 名を編集してください。',
    '',
  ].join('\n');

  const yaml = stringifyYaml(ast, {
    lineWidth: 0,           // 折り返さない
    minContentWidth: 0,
    defaultStringType: 'PLAIN',
    defaultKeyType: 'PLAIN',
  });

  return header + yaml;
}

export async function runIntrospectCommand(argv: readonly string[]): Promise<void> {
  const options = parseArgs(argv);
  if (options.help) {
    process.stdout.write(`pleasync introspect

Usage:
  pleasync introspect <siteId> [<siteId>...] [options]

Options:
  --out <path>       Write YAML to file (default: stdout)
  --base-url <url>   Pleasanter base URL (or PLEASANTER_BASE_URL env)
  --api-key <key>    API key (or PLEASANTER_API_KEY env)
  --api-version <v>  API version (default: 1.1)
  -h, --help         Show this help

Examples:
  pleasync introspect 35535
  pleasync introspect 35535 35536 --out pleasync.schema.yaml
`);
    return;
  }

  const result = await runIntrospect(options);
  if (result.outputPath) {
    process.stdout.write(
      `[pleasync] introspected ${result.modelCount} model(s) -> ${result.outputPath}\n`,
    );
  } else {
    process.stdout.write(result.yaml);
  }
}

function parseArgs(
  argv: readonly string[],
): IntrospectCommandOptions & { help?: boolean } {
  const opts: IntrospectCommandOptions & { help?: boolean } = {
    siteIds: [],
  };

  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '-h' || a === '--help') {
      opts.help = true;
    } else if (a === '--out') {
      opts.out = argv[++i];
    } else if (a === '--base-url') {
      opts.baseUrl = argv[++i];
    } else if (a === '--api-key') {
      opts.apiKey = argv[++i];
    } else if (a === '--api-version') {
      opts.apiVersion = argv[++i];
    } else if (a.startsWith('--')) {
      throw new Error(`unknown option: ${a}`);
    } else {
      const id = Number(a);
      if (!Number.isFinite(id) || id <= 0) {
        throw new Error(`invalid siteId: ${a}`);
      }
      opts.siteIds.push(id);
    }
  }

  return opts;
}
