import type {
  Choice,
  Field,
  FieldType,
  Model,
  SchemaAst,
} from '@pleasync/schema';

export interface GenerateOptions {
  /** schema ファイルのパス（生成コードのコメントに記載） */
  schemaPath?: string;
}

/**
 * SchemaAst から型付きクライアント TS ソースを生成する。
 *
 * 出力は単一の TypeScript ファイル文字列。tsx などの jsx は使わない。
 */
export function generateClient(
  ast: SchemaAst,
  options: GenerateOptions = {},
): string {
  const lines: string[] = [];

  lines.push(buildHeader(options.schemaPath));
  lines.push(buildImports());
  lines.push('');

  // shared choices
  if (ast.choices && Object.keys(ast.choices).length > 0) {
    lines.push('// === shared choices ===');
    for (const [name, list] of Object.entries(ast.choices)) {
      lines.push(`export type ${name} = ${unionFromChoices(list)};`);
    }
    lines.push('');
  }

  // models
  for (const [modelName, model] of Object.entries(ast.models)) {
    lines.push(`// === ${modelName} ===`);
    lines.push(buildModelTypes(modelName, model));
    lines.push(buildCollectionClass(modelName, model));
    lines.push('');
  }

  // top-level client
  lines.push(buildClient(ast.models));

  return lines.join('\n') + '\n';
}

// === helpers ===

function buildHeader(schemaPath?: string): string {
  const from = schemaPath ? `from ${schemaPath} ` : '';
  return [
    '// AUTO-GENERATED — do not edit manually.',
    `// Generated by pleasync ${from}`,
    '',
    '/* eslint-disable */',
    '/* @ts-nocheck */',
  ].join('\n');
}

function buildImports(): string {
  return [
    "import { Engine, ModelCollection } from '@pleasync/orm';",
    "import type { ModelDef, WhereOperator, OrderByDirection } from '@pleasync/orm';",
  ].join('\n');
}

function unionFromChoices(list: Choice[]): string {
  if (list.length === 0) return 'never';
  return list
    .map((c) => (typeof c.value === 'string' ? JSON.stringify(c.value) : String(c.value)))
    .join(' | ');
}

function buildModelTypes(modelName: string, model: Model): string {
  const Pascal = pascalCase(modelName);
  const fields = Object.entries(model.fields);

  const recordLines: string[] = [
    `export interface ${Pascal}Record {`,
    '  id: number;',
  ];
  for (const [name, f] of fields) {
    recordLines.push(`  ${name}: ${tsTypeForRead(f)};`);
  }
  recordLines.push('  createdAt: Date;');
  recordLines.push('  updatedAt: Date;');
  recordLines.push('}');

  const createLines: string[] = [`export interface ${Pascal}CreateInput {`];
  for (const [name, f] of fields) {
    const optional = f.required ? '' : '?';
    createLines.push(`  ${name}${optional}: ${tsTypeForWrite(f)};`);
  }
  createLines.push('}');

  const updateLines: string[] = [`export interface ${Pascal}UpdateInput {`];
  for (const [name, f] of fields) {
    updateLines.push(`  ${name}?: ${tsTypeForWrite(f)};`);
  }
  updateLines.push('}');

  // Where: each field accepts literal value (equals shorthand) or WhereOperator<T>
  const whereLines: string[] = [
    `export interface ${Pascal}Where {`,
    '  id?: WhereOperator<number>;',
  ];
  for (const [name, f] of fields) {
    whereLines.push(`  ${name}?: WhereOperator<${tsTypeForRead(f)}>;`);
  }
  whereLines.push('}');

  // OrderBy: each field optionally takes a direction
  const orderByLines: string[] = [`export interface ${Pascal}OrderBy {`];
  orderByLines.push('  id?: OrderByDirection;');
  for (const [name] of fields) {
    orderByLines.push(`  ${name}?: OrderByDirection;`);
  }
  orderByLines.push('}');

  return [recordLines, createLines, updateLines, whereLines, orderByLines]
    .map((l) => l.join('\n'))
    .join('\n\n');
}

function buildCollectionClass(modelName: string, model: Model): string {
  const Pascal = pascalCase(modelName);
  const fieldMap: string[] = [];
  for (const [name, f] of Object.entries(model.fields)) {
    fieldMap.push(`      ${name}: { slot: ${JSON.stringify(f.slot)}, type: ${JSON.stringify(f.type)} },`);
  }

  const siteIdLiteral =
    typeof model.siteId === 'number'
      ? String(model.siteId)
      : '/* MISSING siteId — run `pleasync apply` to populate */ 0';

  return [
    '',
    `class ${Pascal}Collection extends ModelCollection<`,
    `  ${Pascal}Record,`,
    `  ${Pascal}CreateInput,`,
    `  ${Pascal}UpdateInput,`,
    `  ${Pascal}Where,`,
    `  ${Pascal}OrderBy`,
    '> {',
    `  protected readonly modelDef: ModelDef = {`,
    `    type: ${JSON.stringify(model.type)},`,
    `    parentId: ${model.parentId},`,
    `    siteId: ${siteIdLiteral},`,
    '    fieldMap: {',
    ...fieldMap,
    '    },',
    '  };',
    '}',
  ].join('\n');
}

function buildClient(models: Record<string, Model>): string {
  const modelNames = Object.keys(models);
  const fields = modelNames
    .map((m) => `  readonly ${m}: ${pascalCase(m)}Collection;`)
    .join('\n');
  const inits = modelNames
    .map((m) => `    this.${m} = new ${pascalCase(m)}Collection(engine);`)
    .join('\n');

  return [
    '// === client ===',
    '',
    'export interface PleasyncClientConfig {',
    '  baseUrl: string;',
    '  apiKey: string;',
    "  apiVersion?: string;",
    '}',
    '',
    'export class PleasyncClient {',
    fields,
    '',
    '  private constructor(engine: Engine) {',
    inits,
    '  }',
    '',
    '  /** 設定から PleasyncClient を構築（@pleasync/client を内部 require） */',
    '  static async fromConfig(config: PleasyncClientConfig): Promise<PleasyncClient> {',
    '    const engine = await Engine.fromConfig(config);',
    '    return new PleasyncClient(engine);',
    '  }',
    '',
    '  /** Engine を直接渡す（テスト用） */',
    '  static fromEngine(engine: Engine): PleasyncClient {',
    '    return new PleasyncClient(engine);',
    '  }',
    '}',
  ].join('\n');
}

function tsTypeForRead(field: Field): string {
  return tsTypeForFieldType(field, 'read');
}

function tsTypeForWrite(field: Field): string {
  return tsTypeForFieldType(field, 'write');
}

function tsTypeForFieldType(field: Field, mode: 'read' | 'write'): string {
  switch (field.type) {
    case 'text':
    case 'description':
      return 'string';
    case 'number':
      return 'number';
    case 'datetime':
      return mode === 'read' ? 'Date | string' : 'Date | string';
    case 'boolean':
    case 'check':
      return 'boolean';
    case 'status':
    case 'class': {
      const choices = field.choices;
      if (typeof choices === 'string') {
        // shared choices: 名前を直接型として参照
        return choices;
      }
      if (Array.isArray(choices) && choices.length > 0) {
        return unionFromChoices(choices);
      }
      return 'number | string';
    }
    case 'relation':
      // MVP: 関連レコードの id (number) を保持
      return 'number';
    default:
      return 'unknown';
  }
}

function pascalCase(s: string): string {
  if (s.length === 0) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// FieldType を使っていることを explicit にする（unused import 警告回避）
export type _FieldType = FieldType;
